version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing Packer..."
      - wget https://releases.hashicorp.com/packer/1.8.6/packer_1.8.6_linux_amd64.zip
      - unzip packer_1.8.6_linux_amd64.zip
      - mv packer /usr/local/bin/
      - packer version

  pre_build:
    commands:
      - echo "Pre-build phase started on $(date)"
      - echo "Current directory $(pwd)"
      - echo "Listing files:"
      - ls -la
      - echo "Installing jq for JSON parsing"
      - yum install -y jq
      - echo "Listing sample-app directory:"
      - ls -la sample-app/

  build:
    commands:
      - echo "Build phase started on $(date)"
      - echo "Current directory $(pwd)"
      - echo "Validating Packer template..."
      - cd sample-app && packer validate -var "project_name=$PROJECT_NAME" -var "environment=$ENVIRONMENT" -var "region=$AWS_DEFAULT_REGION" -var "vpc_id=$VPC_ID" -var "subnet_id=$SUBNET_ID" -var "security_group_id=$SECURITY_GROUP_ID" -var "instance_profile=$INSTANCE_PROFILE" packer-template.pkr.hcl
      - echo "Building AMI with Packer..."
      - cd sample-app && packer build -machine-readable -var "project_name=$PROJECT_NAME" -var "environment=$ENVIRONMENT" -var "region=$AWS_DEFAULT_REGION" -var "vpc_id=$VPC_ID" -var "subnet_id=$SUBNET_ID" -var "security_group_id=$SECURITY_GROUP_ID" -var "instance_profile=$INSTANCE_PROFILE" packer-template.pkr.hcl | tee packer.log
      - echo "Extracting AMI ID from Packer output..."
      - cd sample-app && AMI_ID=$(grep 'artifact,0,id' packer.log | cut -d: -f2)
      - cd sample-app && echo "AMI_ID=$AMI_ID" > ami.env
      - cd sample-app && echo "AMI ID $AMI_ID"

artifacts:
  files:
    - "sample-app/ami.env"
    - "sample-app/manifest.json"
  name: packer-artifacts

cache:
  paths:
    - "/usr/local/bin/packer"
