version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing Packer..."
      - wget https://releases.hashicorp.com/packer/1.11.2/packer_1.11.2_linux_amd64.zip
      - unzip packer_1.11.2_linux_amd64.zip
      - mv packer /usr/local/bin/
      - packer version

  pre_build:
    commands:
      - echo "Pre-build phase started on $(date)"
      - echo "Current directory $(pwd)"
      - echo "Listing files:"
      - ls -la
      - echo "Installing jq for JSON parsing"
      - yum install -y jq
      - echo "Initializing Packer plugins..."
      - packer init packer-template.pkr.hcl

  build:
    commands:
      - echo "Build phase started on $(date)"
      - echo "Current directory $(pwd)"
      - echo "Validating Packer template..."
      - |
        packer validate \
          -var "project_name=$PROJECT_NAME" \
          -var "environment=$ENVIRONMENT" \
          -var "region=$AWS_DEFAULT_REGION" \
          -var "vpc_id=$VPC_ID" \
          -var "subnet_id=$SUBNET_ID" \
          -var "security_group_id=$SECURITY_GROUP_ID" \
          -var "instance_profile=$INSTANCE_PROFILE" \
          packer-template.pkr.hcl
      - echo "Building AMI with Packer..."
      - |
        packer build -machine-readable \
          -var "project_name=$PROJECT_NAME" \
          -var "environment=$ENVIRONMENT" \
          -var "region=$AWS_DEFAULT_REGION" \
          -var "vpc_id=$VPC_ID" \
          -var "subnet_id=$SUBNET_ID" \
          -var "security_group_id=$SECURITY_GROUP_ID" \
          -var "instance_profile=$INSTANCE_PROFILE" \
          packer-template.pkr.hcl | tee packer.log
      - echo "Extracting AMI ID from Packer output..."
      - |
        AMI_ID=$(grep 'artifact,0,id' packer.log | cut -d: -f2)
        echo "AMI_ID=$AMI_ID" > ami.env
        echo "AMI ID: $AMI_ID"

artifacts:
  files:
    - "ami.env"
    - "manifest.json"
  name: packer-artifacts

cache:
  paths:
    - "/usr/local/bin/packer"
