version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.19
    commands:
      - echo "Installing Packer..."
      - export PACKER_VERSION=1.9.4
      - wget https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_linux_amd64.zip
      - unzip packer_${PACKER_VERSION}_linux_amd64.zip
      - mv packer /usr/local/bin/
      - chmod +x /usr/local/bin/packer
      - packer version
      - echo "Packer installation completed"

  pre_build:
    commands:
      - echo "Pre-build phase started on $(date)"
      - echo "Current directory: $(pwd)"
      - echo "Listing files:"
      - ls -la
      - echo "Validating Packer template..."
      - packer validate packer-template.pkr.hcl
      - echo "Packer template validation successful"

  build:
    commands:
      - echo "Build phase started on $(date)"
      - echo "Building AMI with Packer..."
      - echo "Environment variables:"
      - echo "  AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION"
      - echo "  PROJECT_NAME: $PROJECT_NAME"
      - echo "  ENVIRONMENT: $ENVIRONMENT"
      - echo "  VPC_ID: $VPC_ID"
      - echo "  SUBNET_ID: $SUBNET_ID"
      - echo "  SECURITY_GROUP_ID: $SECURITY_GROUP_ID"
      - echo "  INSTANCE_PROFILE: $INSTANCE_PROFILE"
      - |
        packer build \
          -var "project_name=$PROJECT_NAME" \
          -var "environment=$ENVIRONMENT" \
          -var "region=$AWS_DEFAULT_REGION" \
          -var "vpc_id=$VPC_ID" \
          -var "subnet_id=$SUBNET_ID" \
          -var "security_group_id=$SECURITY_GROUP_ID" \
          -var "instance_profile=$INSTANCE_PROFILE" \
          packer-template.pkr.hcl

  post_build:
    commands:
      - echo "Post-build phase started on $(date)"
      - echo "AMI build completed successfully"
      - echo "Retrieving AMI ID from Packer output..."
      - |
        if [ -f manifest.json ]; then
          AMI_ID=$(jq -r '.builds[0].artifact_id' manifest.json | cut -d':' -f2)
          echo "Built AMI ID: $AMI_ID"
          echo "AMI_ID=$AMI_ID" >> $CODEBUILD_SOURCE_VERSION.env
        else
          echo "No manifest.json found, AMI ID may be in Packer output"
        fi
      - echo "Build phase completed on $(date)"

artifacts:
  files:
    - '*.env'
  name: packer-artifacts
  
cache:
  paths:
    - '/usr/local/bin/packer'
